#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_White'
kcminputrc_mouse_cursortheme=Neutra
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Default
ksplashrc_ksplash_theme=None
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine=None
# krandrrc Display ApplyOnStartup false
krandrrc_display_applyonstartup=false
# krandrrc Display StartupCommands ''
krandrrc_display_startupcommands=''
# krandrrc [Screen0]
# krandrrc [Screen1]
# krandrrc [Screen2]
# krandrrc [Screen3]
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=''
klocale_languages=en_US
