#! /bin/sh
# kcminputrc Mouse cursorTheme 'Oxygen_White'
kcminputrc_mouse_cursortheme=Neutra
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=0
# ksplashrc KSplash Theme Default
ksplashrc_ksplash_theme=Dharma
# ksplashrc KSplash Engine KSplashX
ksplashrc_ksplash_engine=KSplashQML
# krandrrc Display ApplyOnStartup false
krandrrc_display_applyonstartup=true
# krandrrc Display StartupCommands ''
krandrrc_display_startupcommands='xrandr --output LVDS-1 --pos 0x0 --mode 1440x900 --refresh 59.9297
xrandr --output DP-1 --pos 0x0 --mode 1680x1050 --refresh 59.8833
xrandr --output DP-1 --primary'
# krandrrc [Screen0]
# krandrrc [Screen1]
# krandrrc [Screen2]
# krandrrc [Screen3]
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=0
# kdeglobals Locale Language '' # trigger requesting languages from KLocale
kdeglobals_locale_language=''
klocale_languages=en_GB:en_US
